## Text Cleaning

In [3]:
import pandas as pd

In [4]:
d = pd.read_csv('train_data_cleaning.csv')

In [5]:
d.head()

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this # earthquake...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask . Canada,1
2,5,NaN,NaN,All residents asked to ' shelter in place ' ...,1
3,6,NaN,NaN,"13,000 people receive # wildfires evacuation ...",1
4,7,NaN,NaN,Just got sent this photo from Ruby # Alaska a...,1

## Lower Casing

In [6]:
d.text = d.text.str.lower()

In [7]:
d.info()

<class 'pandas.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        7613 non-null   int64
 1   keyword   7552 non-null   str
 2   location  5080 non-null   str
 3   text      7613 non-null   str
 4   target    7613 non-null   int64
dtypes: int64(2), str(3)
memory usage: 1.1 MB

In [8]:
import re

text = "<h1>Hello my name is Manish</h1>"

re.sub(r'<.*?>', '', text)

'Hello my name is Manish'

In [43]:
data = pd.DataFrame({"col": [
    'Hello <h1> Manish </h1>',
    '<a>click here</a>',
    '<p>How are you?</p>'
]})

In [10]:
def removeTags(text):
    cleaned = []
    for i in text:
        cleaned.append(re.sub(r'<.*?>', '', i))
    return cleaned

In [41]:
data['col'].apply(removeTags)

KeyError: 'col'

In [12]:
text = 'Hii Please Click here to visit my website https://manishAnaya.github.io'

re.sub(r'https?://\S+|www\.\S+', '', text)

'Hii Please Click here to visit my website '

In [13]:
text = 'Hello, Manish!! How are you?'

re.sub(r'[^\w\s]', '', text)

'Hello Manish How are you'

In [14]:
d.text

0       our deeds are the reason of this  # earthquake...
1                forest fire near la ronge sask .  canada
2       all residents asked to  ' shelter in place '  ...
3       13,000 people receive  # wildfires evacuation ...
4       just got sent this photo from ruby  # alaska a...
                              ...
7608    two giant cranes holding a bridge collapse int...
7609     @ aria ahrary  @ thetawniest the out of contr...
7610    m1 . 94  [ 01 : 04 utc ]  ? 5km s of volcano h...
7611    police investigating after an e - bike collide...
7612    the latest :  more homes razed by northern cal...
Name: text, Length: 7613, dtype: str

In [15]:
def remove_panctuation(text):
    return re.sub(r'[^\w\s]', '', text)

In [16]:
d.text.apply(remove_panctuation)

0       our deeds are the reason of this   earthquake ...
1                 forest fire near la ronge sask   canada
2       all residents asked to   shelter in place   ar...
3       13000 people receive   wildfires evacuation or...
4       just got sent this photo from ruby   alaska as...
                              ...
7608    two giant cranes holding a bridge collapse int...
7609      aria ahrary   thetawniest the out of control...
7610    m1  94   01  04 utc    5km s of volcano hawaii
7611    police investigating after an e  bike collided...
7612    the latest   more homes razed by northern cali...
Name: text, Length: 7613, dtype: str

In [17]:
slangs_dict = {
    "gm": "good morning",
    "fomo": "fear of missing out",
    "yolo": "you only live once",
    "asap": "as soon as possible"
}
slangs_dict

{'gm': 'good morning',
 'fomo': 'fear of missing out',
 'yolo': 'you only live once',
 'asap': 'as soon as possible'}

In [18]:
slang_df = pd.DataFrame(
    {"col": ["Hey gm", "I have fomo of that", "Enjoy man because yolo", "Please come asap"]}
)
slang_df

                      col
0                  Hey gm
1     I have fomo of that
2  Enjoy man because yolo
3        Please come asap

In [19]:
def expand_slangs(text):
    words = text.split()
    return " ".join([slangs_dict.get(word, word) for word in words])

In [20]:
slang_df.col = slang_df.col.apply(expand_slangs)
slang_df

                                    col
0                      Hey good morning
1    I have fear of missing out of that
2  Enjoy man because you only live once
3       Please come as soon as possible

## Advnaced Cleaning

#### Spelling correction TEXTBLOB

In [21]:
from textblob import TextBlob

In [22]:
text = "hello, How are you brother?? I m fine and was luoking for you"

In [23]:
txt = TextBlob(text)
txt.correct().string

'hello, Now are you brother?? I m fine and was looking for you'

## Workign with Emojis cleaning

In [24]:
import nltk

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ManishAgrahari\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [25]:
from nltk.corpus import stopwords

In [26]:
len(stopwords.words('english'))

198

In [27]:
english_stop_words = stopwords.words('english')

In [28]:
msg = "Hii How are you I was looking for you.. I am quite exited to eat an apple"

In [29]:
without_stopword = []
for i in msg.split():
    if i in english_stop_words:
        without_stopword.append('')
    else:
        without_stopword.append(i)

In [30]:
" ".join(without_stopword)

'Hii How   I  looking  you.. I  quite exited  eat  apple'

In [31]:
def remove_emojis(text):
    emoji_pattern = re.compile(
        "["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags
        "]+",
        flags=re.UNICODE
    )

    return emoji_pattern.sub(r'', text)

In [32]:
data = {
    "content": [
        "Hello 😊, how are you?",
        "I am learning NLP 🚀 and Python 🐍",
        "This is amazing! 🔥🔥🔥",
        "Good morning ☀️ everyone!",
        "I love India 🇮🇳 ❤️"
    ]
}

data = pd.DataFrame(data)
data

                            content
0             Hello 😊, how are you?
1  I am learning NLP 🚀 and Python 🐍
2              This is amazing! 🔥🔥🔥
3         Good morning ☀️ everyone!
4                I love India 🇮🇳 ❤️

In [33]:
data.content.apply(remove_emojis)

0              Hello , how are you?
1    I am learning NLP  and Python
2                 This is amazing!
3         Good morning ☀️ everyone!
4                  I love India  ❤️
Name: content, dtype: str

## Understanding Emojis

In [34]:
pip install emoji

Requirement already satisfied: emoji in c:\users\manishagrahari\desktop\my_learning\.venv\lib\site-packages (2.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [35]:
import emoji

In [36]:
def emoji_text(text):
    return emoji.demojize(text, delimiters=(" ", " "))

In [37]:
"Hello 😊, how are you?",
"I am learning NLP 🚀 and Python 🐍",
"This is amazing! 🔥🔥🔥",
"Good morning ☀️ everyone!",
"I love India 🇮🇳 ❤️"

'I love India 🇮🇳 ❤️'

In [38]:
sample = "Hello 😊, how are you? I am learning NLP 🚀 and Python 🐍 This is amazing! 🔥🔥🔥 Good morning ☀️ everyone! I love India 🇮🇳 ❤️"

In [39]:
emoji_text(sample)

'Hello  smiling_face_with_smiling_eyes , how are you? I am learning NLP  rocket  and Python  snake  This is amazing!  fire  fire  fire  Good morning  sun  everyone! I love India  India   red_heart '