In [61]:
import pandas as pd

## Reading the csv file

In [62]:
df = pd.read_csv('final_data.csv')

## Dropping unwanted column

In [63]:
df.drop('OrderValue', axis=1, inplace=True)
df.drop('OrderID', axis=1, inplace=True)
df.drop('CustomerID', axis=1, inplace=True)
df.drop('ProductID', axis=1, inplace=True)

## Filling the missing values

In [64]:
df['Age'] = df['Age'].fillna(df['Age'].median()).round().astype('int32')
df['City'] = df['City'].fillna(df['City'].mode()[0])

In [65]:
numerical_cols = ['Quantity', 'Discount', 'Age', 'UnitPrice', 'Sales']
categorical_cols = ['PaymentMethod', 'Status', 'City', 'CustomerSegment', 'ProductName', 'Category']
date_cols = ['OrderDate', 'SignupDate']

## Fixing Incorrect Data types

In [66]:
for col in numerical_cols:
    df[col] = df[col].astype('int32')

for col in categorical_cols:
    df[col] = df[col].astype('category')

for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')

In [67]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49222 entries, 0 to 49221
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderDate        49222 non-null  datetime64[us]
 1   Quantity         49222 non-null  int32
 2   Discount         49222 non-null  int32
 3   PaymentMethod    49222 non-null  category
 4   Status           49222 non-null  category
 5   Age              49222 non-null  int32
 6   City             49222 non-null  category
 7   SignupDate       49222 non-null  datetime64[us]
 8   CustomerSegment  49222 non-null  category
 9   ProductName      49222 non-null  category
 10  Category         49222 non-null  category
 11  UnitPrice        49222 non-null  int32
 12  Sales            49222 non-null  int32
dtypes: category(6), datetime64[us](2), int32(5)
memory usage: 2.0 MB

## Task 1 --> Creating new features

In [68]:
df['AgeGroup'] = pd.cut(df['Age'], bins=[17, 25, 35, 50, 65], labels=['Young', 'Young Adult', 'Adult', 'Senior'])
df['GrossAmount'] = df['Quantity'] * df['UnitPrice']

In [69]:
df.head()

,OrderDate,Quantity,Discount,PaymentMethod,Status,Age,City,SignupDate,CustomerSegment,ProductName,Category,UnitPrice,Sales,AgeGroup,GrossAmount
0,2025-08-28,4,10,Gateway,Completed,36,Qom,2024-03-05,Regular,USB-C Cable,Accessories,9,32,Adult,36
1,2024-05-31,1,10,Wallet,Completed,49,Kerman,2025-06-04,Regular,Backpack,Accessories,42,38,Adult,42
2,2025-08-10,1,20,CardToCard,Completed,36,Tehran,2025-10-19,Regular,Mechanical Keyboard,Electronics,62,50,Adult,62
3,2024-10-11,1,10,Gateway,Completed,45,Shiraz,2023-12-07,Regular,Office Chair,Home Office,180,162,Adult,180
4,2024-02-19,2,0,Gateway,Completed,24,Karaj,2023-12-02,Regular,Phone Case,Accessories,14,28,Young,28

## Task 2 --> Extracting year, month and day -> Extracting length of str columns ->

In [70]:
df['OrderYear'] = df['OrderDate'].dt.year
df['OrderMonth'] = df['OrderDate'].dt.month
df['OrderDay'] = df['OrderDate'].dt.day

In [71]:
df['ProductNameWords'] = df['ProductName'].str.split().str.len()

In [72]:
df.head()

,OrderDate,Quantity,Discount,PaymentMethod,Status,Age,City,SignupDate,CustomerSegment,ProductName,Category,UnitPrice,Sales,AgeGroup,GrossAmount,OrderYear,OrderMonth,OrderDay,ProductNameWords
0,2025-08-28,4,10,Gateway,Completed,36,Qom,2024-03-05,Regular,USB-C Cable,Accessories,9,32,Adult,36,2025,8,28,18
1,2024-05-31,1,10,Wallet,Completed,49,Kerman,2025-06-04,Regular,Backpack,Accessories,42,38,Adult,42,2024,5,31,12
2,2025-08-10,1,20,CardToCard,Completed,36,Tehran,2025-10-19,Regular,Mechanical Keyboard,Electronics,62,50,Adult,62,2025,8,10,26
3,2024-10-11,1,10,Gateway,Completed,45,Shiraz,2023-12-07,Regular,Office Chair,Home Office,180,162,Adult,180,2024,10,11,19
4,2024-02-19,2,0,Gateway,Completed,24,Karaj,2023-12-02,Regular,Phone Case,Accessories,14,28,Young,28,2024,2,19,17

## Task 3 --> One-Hot Encoding

In [ ]:
categorical_cols = ['PaymentMethod', 'Status', 'City', 'CustomerSegment', 'ProductName', 'Category', 'AgeGroup']

df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

df_encoded

## Task 4 --> ColumnTransformer

In [84]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

categorical_features = ['PaymentMethod', 'Status', 'City', 'CustomerSegment', 'ProductName', 'Category', 'AgeGroup']
numerical_features = ['Quantity','Discount','Age','UnitPrice','GrossAmount','OrderYear','OrderMonth','OrderDay','ProductNameWords']

transformer = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features),
        ('num', 'passthrough', numerical_features)
    ]
)

X = df[categorical_features + numerical_features]
X_transformed = transformer.fit_transform(X)

X_transformed.shape

(49222, 59)

## Task 5 --> StandardScaler

#### Standard Scaler transform numerical value so that they are approximately mean(0) and Standard deviation(1).
#### Formula => z = (x - mean) / standard deviation

In [87]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df[numerical_features])
X_scaled.shape

(49222, 9)

## Task 6 --> MinMaxScaler

Xscaled​ = (X - Xmin) / Xmax​ − Xmin​​

In [91]:
from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()
x_minmax = minmax.fit_transform(df[numerical_features])
x_minmax.shape

(49222, 9)

## Task 7 --> Preprocessing Pipeline

In [92]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

categorical_features = ['PaymentMethod', 'Status', 'City', 'CustomerSegment', 'ProductName', 'Category', 'AgeGroup']
numerical_features = ['Quantity','Discount','Age','UnitPrice','GrossAmount','OrderYear','OrderMonth','OrderDay','ProductNameWords']

numeric_pipeline = Pipeline(
    steps=[
        ('impute', SimpleImputer(strategy='mean')),
        ('scale', StandardScaler())
    ]
)

categorical_pipeline = Pipeline(
    steps=[
        ('impute', SimpleImputer(strategy='most_frequent')),
        ('encoding', OneHotEncoder(handle_unknown='ignore'))
    ]
)

features = ColumnTransformer(
    transformers=[
        ('Numerical Feature', numeric_pipeline, numerical_features),
        ('Categorical Features', categorical_pipeline, categorical_features)
    ]
)

features

ColumnTransformer(transformers=[('Numerical Feature',
                                 Pipeline(steps=[('impute', SimpleImputer()),
                                                 ('scale', StandardScaler())]),
                                 ['Quantity', 'Discount', 'Age', 'UnitPrice',
                                  'GrossAmount', 'OrderYear', 'OrderMonth',
                                  'OrderDay', 'ProductNameWords']),
                                ('Categorical Features',
                                 Pipeline(steps=[('impute',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoding',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['PaymentMethod', 'Status', 'City',
                                  'CustomerSegment', 'ProductName', 'Category',
                                  'AgeGroup'])])

## Task 8 --> Full Scikit-learn Pipeline

In [94]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

numeric_pipeline = Pipeline(
    steps=[
        ('impute', SimpleImputer(strategy='mean')),
        ('scale', StandardScaler())
    ]
)

categorical_pipeline = Pipeline(
    steps=[
        ('impute', SimpleImputer(strategy='most_frequent')),
        ('encoding', OneHotEncoder(handle_unknown='ignore'))
    ]
)

features = ColumnTransformer(
    transformers=[
        ('Numerical Feature', numeric_pipeline, numerical_features),
        ('Categorical Features', categorical_pipeline, categorical_features)
    ]
)

model = Pipeline(
    steps=[
        ('features', features),
        ('regression', RandomForestRegressor())
    ]
)

X = df[numerical_features + categorical_features]
Y = df['Sales']

x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

model.fit(x_train, y_train)

y_predict = model.predict(x_test)

mean_absolute_error(y_test, y_predict)

0.03647536820721176

## Task 9 --> Pipeline Benefits

#### 1. Benefits of Pipeline
#### Makes the ML process simple and organized.
#### Automates preprocessing steps.
#### Reduces manual work and errors.
#### Makes the model easier to use and deploy.

#### 2. Problems 
#### Pipeline can be difficult to understand at first.
#### Debugging can be harder when many steps are combined.
#### A small mistake in one step can affect the whole pipeline.
#### It may take some time to set up properly.

#### Difference — Without Pipeline vs With Pipeline
#### Steps are done manually  | Steps are automated
#### More code  |  Less and organized code
#### Higher chance of errors  |  Fewer errors
#### Harder to maintain  |  Easier to maintain