## Auto Cleaning 

### Why Data is missing that have mainly 3 ways =>
#### Missing Completely at Random (MCAR)
#### Missing at Random (MAR)
#### Missing not at Random (MNAR)

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('unclean_smartwatch_health_data.csv')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User ID                 9799 non-null   float64
 1   Heart Rate (BPM)        9600 non-null   float64
 2   Blood Oxygen Level (%)  9700 non-null   float64
 3   Step Count              9900 non-null   float64
 4   Sleep Duration (hours)  9850 non-null   str
 5   Activity Level          9800 non-null   str
 6   Stress Level            9800 non-null   str
dtypes: float64(4), str(3)
memory usage: 811.5 KB

In [8]:
df.isna().sum()

User ID                   201
Heart Rate (BPM)          400
Blood Oxygen Level (%)    300
Step Count                100
Sleep Duration (hours)    150
Activity Level            200
Stress Level              200
dtype: int64

In [9]:
df.drop(columns=['User ID'], inplace=True)

In [10]:
df[df['Heart Rate (BPM)'].isnull() == True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
1,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
17,NaN,96.052853,3488.919508,6.718661172525927,Seddentary,4
75,NaN,100.000000,3124.118038,4.229887888280923,Actve,1
105,NaN,98.276558,3039.112276,5.209658021888749,NaN,6
158,NaN,99.478461,11559.663606,6.470651489160172,Highly_Active,7
...,...,...,...,...,...,...
9875,NaN,99.842527,4454.770218,5.520745925308887,Sedentary,3
9956,NaN,100.000000,3584.236177,6.659533807452561,Highly_Active,5
9971,NaN,99.319841,26.215769,6.367659085134144,Active,10
9990,NaN,100.000000,3817.269018,8.595259517189332,Seddentary,2
9998,NaN,98.401058,3364.788855,5.691233932149209,Active,8

In [11]:
df['Heart Rate (BPM)'].median()

np.float64(75.22060125775644)

In [12]:
df['Heart Rate (BPM)'].describe()

count    9600.000000
mean       76.035462
std        19.412483
min        40.000000
25%        64.890152
50%        75.220601
75%        85.198249
max       296.593970
Name: Heart Rate (BPM), dtype: float64

In [13]:
df['Heart Rate (BPM)'] = df['Heart Rate (BPM)'].fillna(df['Heart Rate (BPM)'].median())

In [14]:
df[df['Blood Oxygen Level (%)'].isnull() == True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
10,101.914938,NaN,2987.568640,7.541956463173237,Sedentary,9
21,68.310104,NaN,1058.374274,6.456918401449286,Actve,3
133,77.907578,NaN,15672.467752,9.079469571860296,Sedentary,10
134,78.227923,NaN,789.365922,3.5252990125882064,Seddentary,3
187,89.486636,NaN,2689.849911,5.737108446097524,Seddentary,6
...,...,...,...,...,...,...
9834,64.803112,NaN,1647.308449,8.04238137746177,Highly Active,7
9861,57.617790,NaN,14269.737149,6.390686112594759,Highly_Active,9
9885,75.281591,NaN,3852.160740,8.970316986352344,Actve,NaN
9905,87.693723,NaN,2364.028205,3.5490963940132865,Seddentary,3
9979,58.797407,NaN,359.210435,8.035879532058063,Active,5

In [15]:
df['Blood Oxygen Level (%)'].describe()

count    9700.000000
mean       97.841581
std         1.732863
min        90.791208
25%        96.662683
50%        98.010642
75%        99.376179
max       100.000000
Name: Blood Oxygen Level (%), dtype: float64

In [16]:
df['Blood Oxygen Level (%)'].median()

np.float64(98.0106416348485)

In [17]:
df['Blood Oxygen Level (%)'] = df['Blood Oxygen Level (%)'].fillna(df['Blood Oxygen Level (%)'].mean())

In [18]:
df['Step Count'].describe()

count     9900.000000
mean      6985.685885
std       6885.809680
min          0.910138
25%       2021.039657
50%       4962.534599
75%       9724.902880
max      62486.690753
Name: Step Count, dtype: float64

In [19]:
df['Step Count'].median()

np.float64(4962.534598525323)

In [20]:
df['Step Count'] = df['Step Count'].fillna(df['Step Count'].median())

In [21]:
df['Sleep Duration (hours)'].describe()

count      9850
unique     9604
top       ERROR
freq        247
Name: Sleep Duration (hours), dtype: object

In [22]:
df['Sleep Duration (hours)'] = pd.to_numeric(df['Sleep Duration (hours)'], errors='coerce')

In [23]:
df['Sleep Duration (hours)'].describe()

count    9603.000000
mean        6.505463
std         1.510029
min        -0.194453
25%         5.493820
50%         6.503308
75%         7.529357
max        12.140233
Name: Sleep Duration (hours), dtype: float64

In [24]:
import numpy as np

In [25]:
df.loc[df['Sleep Duration (hours)'] < 1, 'Sleep Duration (hours)'] = np.nan

In [26]:
df['Sleep Duration (hours)'] = df['Sleep Duration (hours)'].fillna(df['Sleep Duration (hours)'].mean())

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  10000 non-null  float64
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(4), str(2)
memory usage: 571.3 KB

In [28]:
df['Sleep Duration (hours)'].dtypes

dtype('float64')

In [29]:
df['Activity Level'] = df['Activity Level'].str.replace('Highly_Active', 'Highly Active')
df['Activity Level'] = df['Activity Level'].str.replace('Actve', 'Active')
df['Activity Level'] = df['Activity Level'].str.replace('Seddentary', 'Sedentary')

In [30]:
df['Activity Level'].unique()

<ArrowStringArray>
['Highly Active', 'Active', 'Sedentary', nan]
Length: 4, dtype: str

In [31]:
df['Activity Level'] = df['Activity Level'].fillna(df['Activity Level'].mode()[0])

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  10000 non-null  float64
 4   Activity Level          10000 non-null  str
 5   Stress Level            9800 non-null   str
dtypes: float64(4), str(2)
memory usage: 571.8 KB

In [33]:
df[df['Stress Level'].isnull() == True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
13,79.062632,99.014913,829.925623,6.269060,Sedentary,NaN
22,81.267235,96.068161,10503.006243,5.780212,Active,NaN
45,87.135918,97.708276,3437.285884,5.945493,Highly Active,NaN
179,68.809496,99.268945,6254.337835,7.125259,Sedentary,NaN
261,74.268839,97.905483,4333.083235,9.553164,Sedentary,NaN
...,...,...,...,...,...,...
9776,75.220601,95.867583,3056.367782,6.177411,Active,NaN
9826,55.151993,99.312648,40.324128,8.376416,Highly Active,NaN
9868,75.220601,100.000000,12493.577435,3.641176,Sedentary,NaN
9873,43.889444,95.345083,12980.404669,7.140447,Sedentary,NaN
9885,75.281591,97.841581,3852.160740,8.970317,Active,NaN

In [34]:
df['Stress Level'] = pd.to_numeric(df['Stress Level'], errors='coerce')

In [35]:
df['Stress Level'].unique()

array([ 1.,  5.,  3.,  6., 10.,  2.,  8.,  9., nan,  4.,  7.])

In [36]:
df['Stress Level'].describe()

count    9751.000000
mean        5.464055
std         2.871561
min         1.000000
25%         3.000000
50%         5.000000
75%         8.000000
max        10.000000
Name: Stress Level, dtype: float64

In [37]:
df['Stress Level'].mode()

0    2.0
Name: Stress Level, dtype: float64

In [38]:
df['Stress Level'] = df['Stress Level'].fillna(2.0)

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  10000 non-null  float64
 4   Activity Level          10000 non-null  str
 5   Stress Level            10000 non-null  float64
dtypes: float64(5), str(1)
memory usage: 559.7 KB

## Data Clenaing using Sklearn

In [40]:
ndf = pd.read_csv('unclean_smartwatch_health_data.csv')

In [41]:
ndf.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User ID                 9799 non-null   float64
 1   Heart Rate (BPM)        9600 non-null   float64
 2   Blood Oxygen Level (%)  9700 non-null   float64
 3   Step Count              9900 non-null   float64
 4   Sleep Duration (hours)  9850 non-null   str
 5   Activity Level          9800 non-null   str
 6   Stress Level            9800 non-null   str
dtypes: float64(4), str(3)
memory usage: 811.5 KB

In [42]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\manishagrahari\desktop\my_learning\.venv\lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\manishagrahari\desktop\my_learning\.venv\lib\site-packages (from scikit-learn) (2.5.1)
Requirement already satisfied: scipy>=1.10.0 in c:\users\manishagrahari\desktop\my_learning\.venv\lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in c:\users\manishagrahari\desktop\my_learning\.venv\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\manishagrahari\desktop\my_learning\.venv\lib\site-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\manishagrahari\desktop\my_learning\.venv\lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [43]:
from sklearn.impute import SimpleImputer

In [44]:
imputer = SimpleImputer(strategy='mean')

In [47]:
ndf['Heart Rate (BPM)'] = imputer.fit_transform(ndf[['Heart Rate (BPM)']]).ravel()

In [49]:
ndf['Blood Oxygen Level (%)'] = imputer.fit_transform(ndf[['Blood Oxygen Level (%)']]).ravel()

In [53]:
ndf.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User ID                 9799 non-null   float64
 1   Heart Rate (BPM)        10000 non-null  float64
 2   Blood Oxygen Level (%)  10000 non-null  float64
 3   Step Count              9900 non-null   float64
 4   Sleep Duration (hours)  9850 non-null   str
 5   Activity Level          9800 non-null   str
 6   Stress Level            10000 non-null  object
dtypes: float64(4), object(1), str(2)
memory usage: 799.3+ KB

In [55]:
ndf['Stress Level'].dtypes

dtype('O')

In [51]:
imputer = SimpleImputer(strategy='constant', fill_value=5)

In [52]:
ndf['Stress Level'] = imputer.fit_transform(ndf[['Stress Level']]).ravel()

In [ ]:
imputer = SimpleImputer(strategy='')