## Task 1 -> NLP Pipeline & Basic Text Cleaning -> Understand Raw Text Data

In [97]:
import pandas as pd

# creating my own dataset and converting it into dataframe

df = pd.DataFrame({'content': [
    "WOW!!! This movie is SOOOO good 😍",
    "I bought this product for 999 rupees!!!",
    "mail us at test@gmail.com for any query.",
    "Contact me at test@gmail.com ASAP.",
    "<p>This movie was AMAZING!</p>",
    "I am soooo happy with this service!!!",
    "u r gr8 bro",
    "The product is GOOD... but delivery was SLOW.",
    "I waited 2 HOURS for my order!!!",
    "This is    a very    good product.",
    "OMG!!! This phone is absolutely AMAZING!!! 🔥",
    "The price is only 1499 and the quality is excellent.",    
    "Check www.example.com for the latest offers.",    
    "Please email support@company.com for help.",    
    "<div>This product is worth buying.</div>",    
    "The delivery was reallllllly fast!!!",    
    "I loooooove this product ❤️",    
    "idk why the delivery was so late :(",    
    "This movie was kinda boring but the acting was GREAT.",    
    "The service was bad!!! Very bad!!!",    
    "I ordered it yesterday at 10:30 PM.",    
    "     The product arrived in perfect condition.     ",    
    "This product is 100% genuine & reliable.",    
    "u should definitely buy this product!!!",    
    "The camera quality is sooo sooo good 😍",    
    "I am very happy with my purchase :)",    
    "This app is AWESOME!!! Download it now!!!",    
    "The customer support team was helpful... but response was slow.",    
    "OMG!!! Why is this product soooo expensive??? 😡",    
    "gr8 product, fast delivery, totally worth it!!!"
]
})

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   content  30 non-null     str
dtypes: str(1)
memory usage: 1.5 KB

In [98]:
# First five text sample
df.head()

                                    content
0         WOW!!! This movie is SOOOO good 😍
1   I bought this product for 999 rupees!!!
2  mail us at test@gmail.com for any query.
3        Contact me at test@gmail.com ASAP.
4            <p>This movie was AMAZING!</p>

In [99]:
# Length of each text
df['content'].str.len()

0     33
1     39
2     40
3     34
4     30
5     37
6     11
7     45
8     32
9     34
10    44
11    52
12    44
13    42
14    40
15    36
16    27
17    35
18    53
19    34
20    35
21    51
22    40
23    39
24    38
25    35
26    41
27    63
28    47
29    47
Name: content, dtype: int64

## Identifying some common issue in raw text

#### Upper and Lower case
#### Repeated characters
#### URLs
#### Slangs
#### Email
#### Numbers
#### Extra White Spaces
#### HTML tags
#### Emojis and Special characters
#### Punctuation Marks

## Task 2 -> NLP Pipeline & Basic Text Cleaning -> Advanced Text Cleaning

In [100]:
# Converting text to lowercase
df['content'] = df['content'].str.lower()

In [101]:
import re

# Basic cleaning using re i.e. regular expression

def basic_clean(text):
    # Removing punctuation 
    text = re.sub(r'[!"#$%&\'()*+,-;=?[\\\]^_`{|}~]', '', text)

    # Remove numbers
    text = re.sub(r'\d+', '', text)

    # Remove extra whitespaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [102]:
df['clean_text_basic'] = df['content'].apply(basic_clean)

In [103]:
## Comparing both
df.head(10)

,content,clean_text_basic
0,wow!!! this movie is soooo good 😍,wow this movie is soooo good 😍
1,i bought this product for 999 rupees!!!,i bought this product for rupees
2,mail us at test@gmail.com for any query.,mail us at test@gmailcom for any query
3,contact me at test@gmail.com asap.,contact me at test@gmailcom asap
4,<p>this movie was amazing!</p>,<p>this movie was amazing<p>
5,i am soooo happy with this service!!!,i am soooo happy with this service
6,u r gr8 bro,u r gr bro
7,the product is good... but delivery was slow.,the product is good but delivery was slow
8,i waited 2 hours for my order!!!,i waited hours for my order
9,this is a very good product.,this is a very good product

## Task 3 -> Advanced Text Cleaning -> Removing Noise

In [104]:
## Advanced Text Cleaning

def advance_cleaning(text):
    # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    
    # Remove email
    text = re.sub(r'\S+@\S+', '', text)
    
    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)
    
    # Remove special characters and emojis
    text = re.sub(r'[^\w\s]', '', text)

    # Remove extra whitespaces created after above steps
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [105]:
df["clean_text_advanced"] = df['clean_text_basic'].apply(advance_cleaning)

In [106]:
df

,content,clean_text_basic,clean_text_advanced
0,wow!!! this movie is soooo good 😍,wow this movie is soooo good 😍,wow this movie is soooo good
1,i bought this product for 999 rupees!!!,i bought this product for rupees,i bought this product for rupees
2,mail us at test@gmail.com for any query.,mail us at test@gmailcom for any query,mail us at for any query
3,contact me at test@gmail.com asap.,contact me at test@gmailcom asap,contact me at asap
4,<p>this movie was amazing!</p>,<p>this movie was amazing<p>,this movie was amazing
5,i am soooo happy with this service!!!,i am soooo happy with this service,i am soooo happy with this service
6,u r gr8 bro,u r gr bro,u r gr bro
7,the product is good... but delivery was slow.,the product is good but delivery was slow,the product is good but delivery was slow
8,i waited 2 hours for my order!!!,i waited hours for my order,i waited hours for my order
9,this is a very good product.,this is a very good product,this is a very good product
10,omg!!! this phone is absolutely amazing!!! 🔥,omg this phone is absolutely amazing 🔥,omg this phone is absolutely amazing
11,the price is only 1499 and the quality is exce...,the price is only and the quality is excellent,the price is only and the quality is excellent
12,check www.example.com for the latest offers.,check wwwexamplecom for the latest offers,check wwwexamplecom for the latest offers
13,please email support@company.com for help.,please email support@companycom for help,please email for help
14,<div>this product is worth buying.</div>,<div>this product is worth buying<div>,this product is worth buying
15,the delivery was reallllllly fast!!!,the delivery was reallllllly fast,the delivery was reallllllly fast
16,i loooooove this product ❤️,i loooooove this product ❤️,i loooooove this product
17,idk why the delivery was so late :(,idk why the delivery was so late,idk why the delivery was so late
18,this movie was kinda boring but the acting was...,this movie was kinda boring but the acting was...,this movie was kinda boring but the acting was...
19,the service was bad!!! very bad!!!,the service was bad very bad,the service was bad very bad
20,i ordered it yesterday at 10:30 pm.,i ordered it yesterday at pm,i ordered it yesterday at pm
21,the product arrived in perfect condition....,the product arrived in perfect condition,the product arrived in perfect condition
22,this product is 100% genuine & reliable.,this product is genuine reliable,this product is genuine reliable
23,u should definitely buy this product!!!,u should definitely buy this product,u should definitely buy this product
24,the camera quality is sooo sooo good 😍,the camera quality is sooo sooo good 😍,the camera quality is sooo sooo good
25,i am very happy with my purchase :),i am very happy with my purchase,i am very happy with my purchase
26,this app is awesome!!! download it now!!!,this app is awesome download it now,this app is awesome download it now
27,the customer support team was helpful... but r...,the customer support team was helpful but resp...,the customer support team was helpful but resp...
28,omg!!! why is this product soooo expensive??? 😡,omg why is this product soooo expensive 😡,omg why is this product soooo expensive
29,"gr8 product, fast delivery, totally worth it!!!",gr product fast delivery totally worth it,gr product fast delivery totally worth it

## Task 4 -> Handling Stopwords

In [107]:
from nltk.corpus import stopwords

en_stop_words = stopwords.words('english')

def remove_stop_words(text):
    clean_words = []
    for word in text.split():
        if word not in en_stop_words:
            clean_words.append(word)
    return " ".join(clean_words)

df['text_no_stopwords'] = df['clean_text_advanced'].apply(remove_stop_words)

In [108]:
df

,content,clean_text_basic,clean_text_advanced,text_no_stopwords
0,wow!!! this movie is soooo good 😍,wow this movie is soooo good 😍,wow this movie is soooo good,wow movie soooo good
1,i bought this product for 999 rupees!!!,i bought this product for rupees,i bought this product for rupees,bought product rupees
2,mail us at test@gmail.com for any query.,mail us at test@gmailcom for any query,mail us at for any query,mail us query
3,contact me at test@gmail.com asap.,contact me at test@gmailcom asap,contact me at asap,contact asap
4,<p>this movie was amazing!</p>,<p>this movie was amazing<p>,this movie was amazing,movie amazing
5,i am soooo happy with this service!!!,i am soooo happy with this service,i am soooo happy with this service,soooo happy service
6,u r gr8 bro,u r gr bro,u r gr bro,u r gr bro
7,the product is good... but delivery was slow.,the product is good but delivery was slow,the product is good but delivery was slow,product good delivery slow
8,i waited 2 hours for my order!!!,i waited hours for my order,i waited hours for my order,waited hours order
9,this is a very good product.,this is a very good product,this is a very good product,good product
10,omg!!! this phone is absolutely amazing!!! 🔥,omg this phone is absolutely amazing 🔥,omg this phone is absolutely amazing,omg phone absolutely amazing
11,the price is only 1499 and the quality is exce...,the price is only and the quality is excellent,the price is only and the quality is excellent,price quality excellent
12,check www.example.com for the latest offers.,check wwwexamplecom for the latest offers,check wwwexamplecom for the latest offers,check wwwexamplecom latest offers
13,please email support@company.com for help.,please email support@companycom for help,please email for help,please email help
14,<div>this product is worth buying.</div>,<div>this product is worth buying<div>,this product is worth buying,product worth buying
15,the delivery was reallllllly fast!!!,the delivery was reallllllly fast,the delivery was reallllllly fast,delivery reallllllly fast
16,i loooooove this product ❤️,i loooooove this product ❤️,i loooooove this product,loooooove product
17,idk why the delivery was so late :(,idk why the delivery was so late,idk why the delivery was so late,idk delivery late
18,this movie was kinda boring but the acting was...,this movie was kinda boring but the acting was...,this movie was kinda boring but the acting was...,movie kinda boring acting great
19,the service was bad!!! very bad!!!,the service was bad very bad,the service was bad very bad,service bad bad
20,i ordered it yesterday at 10:30 pm.,i ordered it yesterday at pm,i ordered it yesterday at pm,ordered yesterday pm
21,the product arrived in perfect condition....,the product arrived in perfect condition,the product arrived in perfect condition,product arrived perfect condition
22,this product is 100% genuine & reliable.,this product is genuine reliable,this product is genuine reliable,product genuine reliable
23,u should definitely buy this product!!!,u should definitely buy this product,u should definitely buy this product,u definitely buy product
24,the camera quality is sooo sooo good 😍,the camera quality is sooo sooo good 😍,the camera quality is sooo sooo good,camera quality sooo sooo good
25,i am very happy with my purchase :),i am very happy with my purchase,i am very happy with my purchase,happy purchase
26,this app is awesome!!! download it now!!!,this app is awesome download it now,this app is awesome download it now,app awesome download
27,the customer support team was helpful... but r...,the customer support team was helpful but resp...,the customer support team was helpful but resp...,customer support team helpful response slow
28,omg!!! why is this product soooo expensive??? 😡,omg why is this product soooo expensive 😡,omg why is this product soooo expensive,omg product soooo expensive
29,"gr8 product, fast delivery, totally worth it!!!",gr product fast delivery totally worth it,gr product fast delivery totally worth it,gr product fast delivery totally worth

## Task 5 -> Repeated Characters & Slang Normalization

In [109]:
## For removing and normalizing repeated words
def normalize_repeated(text):
    text = re.sub(r'(.)\1{2,}', r'\1\1', text)
    return text

## Slangs and its full expanded form in dictionary
slangs_dict = {
    "u": "you",
    "r": "are",
    "gr": "great",
    "idk": "i don't know",
    "asap": "as soon as possible",
    "omg": "oh my god",
    "bro": "brother"
}

## For expanding the slangs using slangs_dict
def expand_slangs(text):
    words = text.split()
    return " ".join([slangs_dict.get(word, word) for word in words])

In [110]:
df['final'] = df['text_no_stopwords'].apply(normalize_repeated)
df['final'] = df['final'].apply(expand_slangs)
df

,content,clean_text_basic,clean_text_advanced,text_no_stopwords,final
0,wow!!! this movie is soooo good 😍,wow this movie is soooo good 😍,wow this movie is soooo good,wow movie soooo good,wow movie soo good
1,i bought this product for 999 rupees!!!,i bought this product for rupees,i bought this product for rupees,bought product rupees,bought product rupees
2,mail us at test@gmail.com for any query.,mail us at test@gmailcom for any query,mail us at for any query,mail us query,mail us query
3,contact me at test@gmail.com asap.,contact me at test@gmailcom asap,contact me at asap,contact asap,contact as soon as possible
4,<p>this movie was amazing!</p>,<p>this movie was amazing<p>,this movie was amazing,movie amazing,movie amazing
5,i am soooo happy with this service!!!,i am soooo happy with this service,i am soooo happy with this service,soooo happy service,soo happy service
6,u r gr8 bro,u r gr bro,u r gr bro,u r gr bro,you are great brother
7,the product is good... but delivery was slow.,the product is good but delivery was slow,the product is good but delivery was slow,product good delivery slow,product good delivery slow
8,i waited 2 hours for my order!!!,i waited hours for my order,i waited hours for my order,waited hours order,waited hours order
9,this is a very good product.,this is a very good product,this is a very good product,good product,good product
10,omg!!! this phone is absolutely amazing!!! 🔥,omg this phone is absolutely amazing 🔥,omg this phone is absolutely amazing,omg phone absolutely amazing,oh my god phone absolutely amazing
11,the price is only 1499 and the quality is exce...,the price is only and the quality is excellent,the price is only and the quality is excellent,price quality excellent,price quality excellent
12,check www.example.com for the latest offers.,check wwwexamplecom for the latest offers,check wwwexamplecom for the latest offers,check wwwexamplecom latest offers,check wwexamplecom latest offers
13,please email support@company.com for help.,please email support@companycom for help,please email for help,please email help,please email help
14,<div>this product is worth buying.</div>,<div>this product is worth buying<div>,this product is worth buying,product worth buying,product worth buying
15,the delivery was reallllllly fast!!!,the delivery was reallllllly fast,the delivery was reallllllly fast,delivery reallllllly fast,delivery really fast
16,i loooooove this product ❤️,i loooooove this product ❤️,i loooooove this product,loooooove product,loove product
17,idk why the delivery was so late :(,idk why the delivery was so late,idk why the delivery was so late,idk delivery late,i don't know delivery late
18,this movie was kinda boring but the acting was...,this movie was kinda boring but the acting was...,this movie was kinda boring but the acting was...,movie kinda boring acting great,movie kinda boring acting great
19,the service was bad!!! very bad!!!,the service was bad very bad,the service was bad very bad,service bad bad,service bad bad
20,i ordered it yesterday at 10:30 pm.,i ordered it yesterday at pm,i ordered it yesterday at pm,ordered yesterday pm,ordered yesterday pm
21,the product arrived in perfect condition....,the product arrived in perfect condition,the product arrived in perfect condition,product arrived perfect condition,product arrived perfect condition
22,this product is 100% genuine & reliable.,this product is genuine reliable,this product is genuine reliable,product genuine reliable,product genuine reliable
23,u should definitely buy this product!!!,u should definitely buy this product,u should definitely buy this product,u definitely buy product,you definitely buy product
24,the camera quality is sooo sooo good 😍,the camera quality is sooo sooo good 😍,the camera quality is sooo sooo good,camera quality sooo sooo good,camera quality soo soo good
25,i am very happy with my purchase :),i am very happy with my purchase,i am very happy with my purchase,happy purchase,happy purchase
26,this app is awesome!!! download it now!!!,this app is awesome download it now,this app is awesome download it now,app awesome download,app awesome download
27,the customer support team was helpful... but r...,the customer support team was helpful but resp...,the customer support team was helpful but resp...,customer support team helpful response slow,customer support team helpful response slow
28,omg!!! why is this product soooo expensive??? 😡,omg why is this product soooo expensive 😡,omg why is this product soooo expensive,omg product soooo expensive,oh my god product soo expensive
29,"gr8 product, fast delivery, totally worth it!!!",gr product fast delivery totally worth it,gr product fast delivery totally worth it,gr product fast delivery totally worth,great product fast delivery totally worth

## Task 6 -> Tokenization

In [111]:
from nltk.tokenize import word_tokenize

# Applying word_tokenize to final cleaned text and saving it to df with new column 
df['word_tokens'] = df['final'].apply(word_tokenize)
df[['final', 'word_tokens']].head(3)

                   final                word_tokens
0     wow movie soo good    [wow, movie, soo, good]
1  bought product rupees  [bought, product, rupees]
2          mail us query          [mail, us, query]

In [112]:
## For sentence Tokenize
from nltk.tokenize import sent_tokenize

# Applying sent_tokenize to final cleaned text and saving it to df with new column 
df['sent_tokens'] = df['final'].apply(sent_tokenize)
df[['final', 'sent_tokens']].head(3)

                   final              sent_tokens
0     wow movie soo good     [wow movie soo good]
1  bought product rupees  [bought product rupees]
2          mail us query          [mail us query]

## Task 7 -> Stemming

In [113]:
from nltk.stem import PorterStemmer

ps = PorterStemmer()

# function to apply stemming in our tokens which are in list
def apply_stemming(tokens):
    stemed_list = []
    for word in tokens:
        stemed_list.append(ps.stem(word))
    return " ".join(stemed_list)

In [114]:
df["stemmed_tokens"] = df["word_tokens"].apply(apply_stemming)
df[["word_tokens", "stemmed_tokens"]].head(5)

                         word_tokens              stemmed_tokens
0            [wow, movie, soo, good]           wow movi soo good
1          [bought, product, rupees]         bought product rupe
2                  [mail, us, query]               mail us queri
3  [contact, as, soon, as, possible]  contact as soon as possibl
4                   [movie, amazing]                   movi amaz

## Task 8 -> Lemmatization

In [115]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

# function to apply lemmatization in our tokens which are in list
def apply_lemmatization(tokens):
    lemmatized_words = []
    for word in tokens:
        lemmatized_words.append(lemmatizer.lemmatize(word))
    return lemmatized_words

In [116]:
df["lemmatized_tokens"] = df["word_tokens"].apply(apply_lemmatization)
df[["word_tokens", "lemmatized_tokens"]].head(5)

                         word_tokens                lemmatized_tokens
0            [wow, movie, soo, good]          [wow, movie, soo, good]
1          [bought, product, rupees]         [bought, product, rupee]
2                  [mail, us, query]                 [mail, u, query]
3  [contact, as, soon, as, possible]  [contact, a, soon, a, possible]
4                   [movie, amazing]                 [movie, amazing]

## Task 9 -> Final NLP pipeline creation

In [120]:
## Starting with all import and initializing some packages

import re
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import  word_tokenize
from nltk.stem import WordNetLemmatizer

# Make sure resource are available if not downlaod using below commands
# nltk.download('punkt')
# nltk.download('punkt_tab')
# nltk.download('stopwords')
# nltk.download('wordnet')
# nltk.download('omw-1.4')

en_stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()
slangs_dict = {
    "u": "you",
    "r": "are",
    "gr8": "great",
    "idk": "i don't know",
    "asap": "as soon as possible",
    "omg": "oh my god",
    "bro": "brother"
}

In [124]:
def final_nlp_pipeline(text):

    # Lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', '', text)

    # Remove email addresses
    text = re.sub(r'\S+@\S+', '', text)
    
    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)
    
    # Remove numbers
    text = re.sub(r'\d+', '', text)
    
    # Removing punctuation 
    text = re.sub(r'[!"#$%&\'()*+,-;=?[\\\]^_`{|}~]', '', text)

    # Remove special characters and emojis
    text = re.sub(r'[^\w\s]', '', text)
    
    # Normalize repeated characters
    text = re.sub(r'(.)\1{2,}', r'\1\1', text)
    
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    # Expand Slangs
    words = text.split()
    expanded_words = [slangs_dict.get(word, word) for word in words]

    # Stop word removal
    filtered_words = []
    for word in expanded_words:
        if word not in en_stop_words:
            filtered_words.append(word)

    # Tokenization
    tokens = word_tokenize(" ".join(filtered_words))

    # Lemmatization
    lemmatized_words = []
    for word in tokens:
        lemmatized_words.append(lemmatizer.lemmatize(word))

    return " ".join(lemmatized_words)

In [125]:
df["final_processed_text"] = df["content"].apply(final_nlp_pipeline)
df[["content", "final_processed_text"]].head(10)

                                         content        final_processed_text
0              wow!!! this movie is soooo good 😍          wow movie soo good
1        i bought this product for 999 rupees!!!        bought product rupee
2       mail us at test@gmail.com for any query.                mail u query
3             contact me at test@gmail.com asap.   contact a soon a possible
4                 <p>this movie was amazing!</p>               movie amazing
5          i am soooo happy with this service!!!           soo happy service
6                                    u r gr8 bro                  gr brother
7  the product is good... but delivery was slow.  product good delivery slow
8               i waited 2 hours for my order!!!           waited hour order
9             this is    a very    good product.                good product

## Task 10 -> Observations & Insights

## 1.
#### Basic Cleaning handles common and simple text cleaning such as lowercase, punctuation, removing numbers,removing whitespaces etc.
#### Advanced Cleaning handles more specific types of noise such as URL's, emails, HTML tags, emojis, special characters, slangs etc.

## 2.
#### Lemmatization is preferred over stemming because it uses linguistic information to convert a word into its meaningful dictionary or its base form becuase
#### Stemming may produce a word that is not a valid English word because it mainly removes prefixes or suffixes using rules. Lemmatization generally produces a more meaningful base word.

## 3.
#### Preprocessing removes noise, normalizes text, and converts raw text into a consistent form. This helps subsequent NLP algorithms process text more effectively.